{
    "schemes": [
        "https"
    ],
    "swagger": "2.0",
    "info": {
        "description": "this application provides API for the NERDZ Social Networking Platform.",
        "title": "NERDZ API.",
        "termsOfService": "there are no TOS at this moment, use at your own risk we take no responsibility",
        "contact": {
            "name": "Paolo Galeone",
            "url": "https://www.nerdz.eu/nessuno.",
            "email": "nessuno@nerdz.eu"
        },
        "license": {
            "name": "AGPL",
            "url": "http://www.gnu.org/licenses/"
        },
        "version": "1"
    },
    "host": "api.nerdz.eu",
    "basePath": "/v1",
    "paths": {
        "/me": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "info"
                ],
                "summary": "Shows the basic informations for the specified user",
                "operationId": "GetMeInfo"
            }
        },
        "/me/blacklist": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "info",
                    "blacklist"
                ],
                "summary": "Shows the blacklist informations for the current user",
                "operationId": "getMeBlacklist"
            }
        },
        "/me/blacklist/{target}": {
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile:write"
                        ]
                    }
                ],
                "description": "Adds target to the blacklist of the current user",
                "tags": [
                    "me",
                    "blacklist"
                ],
                "operationId": "NewBlacklisted"
            }
        },
        "/me/blacklisting": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "info",
                    "blacklisting"
                ],
                "summary": "Shows the blacklisting informations for the current user",
                "operationId": "getMeBlacklisting"
            }
        },
        "/me/followers": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "info",
                    "followers"
                ],
                "summary": "Shows the followers informations for the specified user",
                "operationId": "GetMeFollowers"
            }
        },
        "/me/following/projects": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "project",
                    "info",
                    "following"
                ],
                "summary": "Shows the following informations for the specified user",
                "operationId": "GetMeProjectFollowing"
            }
        },
        "/me/following/projects/{target}": {
            "post": {
                "security": [
                    {
                        "oauth": [
                            "following:write"
                        ]
                    }
                ],
                "description": "Adds target project to the following list of the current user",
                "tags": [
                    "project",
                    "following"
                ],
                "operationId": "NewProjectFollowing"
            }
        },
        "/me/following/users": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "info",
                    "following"
                ],
                "summary": "Shows the following informations for the specified user",
                "operationId": "GetMeFollowing"
            }
        },
        "/me/following/users/{target}": {
            "post": {
                "security": [
                    {
                        "oauth": [
                            "following:write"
                        ]
                    }
                ],
                "description": "Adds target to the following list of the current user",
                "tags": [
                    "me",
                    "userfollowing"
                ],
                "operationId": "NewMeFollowing"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "profile:write"
                        ]
                    }
                ],
                "description": "Deletes target user from the current user blacklist",
                "tags": [
                    "me",
                    "blacklist"
                ],
                "operationId": "DeleteBlacklisted"
            }
        },
        "/me/friends": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "info",
                    "friends"
                ],
                "summary": "Shows the friends informations for the specified user",
                "operationId": "GetMeFriends"
            }
        },
        "/me/home": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "post",
                    "home"
                ],
                "summary": "Shows the homepage of the current user, mixing projects and users posts",
                "operationId": "getMeHome"
            }
        },
        "/me/pms": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "post",
                    "pms"
                ],
                "summary": "Shows the list of the private conversation of the current user",
                "operationId": "getMePms"
            }
        },
        "/me/pms/{other}": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "post",
                    "pms"
                ],
                "summary": "Returns the private conversation of the current user with the other user",
                "operationId": "getMeConversation"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "pms:write"
                        ]
                    }
                ],
                "description": "Creates a new pm with from me to other user",
                "tags": [
                    "me",
                    "pm"
                ],
                "operationId": "NewMePm"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "pms:write"
                        ]
                    }
                ],
                "description": "Delete the conversation beteen the current user and other",
                "tags": [
                    "me",
                    "pms"
                ],
                "operationId": "DeleteMePms"
            }
        },
        "/me/pms/{other}/{pmid}": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "pms:read"
                        ]
                    }
                ],
                "description": "Update the speficied post on the specified user board",
                "tags": [
                    "me",
                    "pms"
                ],
                "operationId": "GetMePm"
            },
            "put": {
                "security": [
                    {
                        "oauth": [
                            "pms:write"
                        ]
                    }
                ],
                "description": "Update the speficied pm in the conversation with the other user",
                "tags": [
                    "me",
                    "pm"
                ],
                "operationId": "EditMePm"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "pms:write"
                        ]
                    }
                ],
                "description": "Delete the speficied pm in the conversation with the other user",
                "tags": [
                    "me",
                    "pm"
                ],
                "operationId": "DeleteMePm"
            }
        },
        "/me/posts": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:read"
                        ]
                    }
                ],
                "description": "This will show the last posts on the user board by default.\nYou can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "posts"
                ],
                "summary": "List posts on user board, filtered by some parameters.",
                "operationId": "GetMePosts"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Creates a new post on the specified user board",
                "tags": [
                    "me",
                    "post"
                ],
                "operationId": "NewMePost"
            }
        },
        "/me/posts/{pid}": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:read"
                        ]
                    }
                ],
                "description": "This will show the last comments on the post by default.\nYou can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "post"
                ],
                "summary": "Shows selected posts with id pid on specified user board",
                "operationId": "GetMePost"
            },
            "put": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Update the speficied post on the specified user board",
                "tags": [
                    "me",
                    "post"
                ],
                "operationId": "EditMePost"
            }
        },
        "/me/posts/{pid}/bookmarks": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:read"
                        ]
                    }
                ],
                "description": "List the bookmarks of the post",
                "tags": [
                    "me",
                    "post",
                    "bookmarks"
                ],
                "operationId": "GetMePostBookmarks"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Adds a new bookmark on the current post",
                "tags": [
                    "me",
                    "post",
                    "vote"
                ],
                "operationId": "NewMePostBookmark"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Deletes the bookmark on the current post",
                "tags": [
                    "me",
                    "post",
                    "vote"
                ],
                "operationId": "DeleteMePostBookmark"
            }
        },
        "/me/posts/{pid}/comments": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:read"
                        ]
                    }
                ],
                "description": "This will show the last posts on the user board by default.\nYou can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "post",
                    "comments"
                ],
                "summary": "List comments on specified post, filtered by some parameters.",
                "operationId": "GetMePostComments"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:write"
                        ]
                    }
                ],
                "description": "Creates a new post on the specified user board",
                "tags": [
                    "me",
                    "post"
                ],
                "operationId": "NewMePostComment"
            }
        },
        "/me/posts/{pid}/comments/{cid}": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "post",
                    "comment"
                ],
                "summary": "Shows selected comment on specified post, filtered by some parameters.",
                "operationId": "GetMePostComment"
            },
            "put": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:write"
                        ]
                    }
                ],
                "description": "Update the speficied post on the specified user board",
                "tags": [
                    "me",
                    "post",
                    "comment"
                ],
                "operationId": "EditMeComment"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:write"
                        ]
                    }
                ],
                "description": "Delete the specified comment on the speficied user post",
                "tags": [
                    "me",
                    "post"
                ],
                "operationId": "DeleteMePost"
            }
        },
        "/me/posts/{pid}/comments/{cid}/votes": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:read"
                        ]
                    }
                ],
                "description": "List the votes on the comment",
                "tags": [
                    "me",
                    "post",
                    "comments",
                    "votes"
                ],
                "operationId": "GetMePostCommentsVotes"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:write"
                        ]
                    }
                ],
                "description": "Adds a new vote on the current user post comment",
                "tags": [
                    "me",
                    "post",
                    "comment",
                    "vote"
                ],
                "operationId": "NewMePostCommentVote"
            }
        },
        "/me/posts/{pid}/locks": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:read"
                        ]
                    }
                ],
                "description": "List the locks of the post",
                "tags": [
                    "me",
                    "post",
                    "locks"
                ],
                "operationId": "GetMePostLock"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Adds a new lock on the current post",
                "tags": [
                    "me",
                    "post",
                    "vote"
                ],
                "operationId": "NewMePostLock"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Deletes the lock on the current post",
                "tags": [
                    "me",
                    "post",
                    "vote"
                ],
                "operationId": "DeleteMePostLock"
            }
        },
        "/me/posts/{pid}/locks/{target}": {
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Locks the notification from the target user to the current logged user, on the specified post",
                "tags": [
                    "me",
                    "post",
                    "vote"
                ],
                "operationId": "NewMeNewPostUserLock"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Deletes the lock  for the notification of the target user on the specified post",
                "tags": [
                    "me",
                    "post",
                    "vote"
                ],
                "operationId": "DeleteMePostUserLock"
            }
        },
        "/me/posts/{pid}/lurks": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:read"
                        ]
                    }
                ],
                "description": "List the lurks of the post",
                "tags": [
                    "me",
                    "post",
                    "bookmarks"
                ],
                "operationId": "GetMePostLurks"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Adds a new lurk on the current post",
                "tags": [
                    "me",
                    "post",
                    "vote"
                ],
                "operationId": "NewMePostLurk"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Deletes the lurk on the current post",
                "tags": [
                    "me",
                    "post",
                    "vote"
                ],
                "operationId": "DeleteMePostLurk"
            }
        },
        "/me/posts/{pid}/votes": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:read"
                        ]
                    }
                ],
                "description": "List the votes of the post",
                "tags": [
                    "me",
                    "post",
                    "votes"
                ],
                "operationId": "GetMePostVotes"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Adds a new vote on the current post",
                "tags": [
                    "me",
                    "post",
                    "vote"
                ],
                "operationId": "NewMePostVote"
            }
        },
        "/me/whitelist": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "info",
                    "whitelist"
                ],
                "summary": "Shows the whitelist informations for the current user",
                "operationId": "getMeWhitelist"
            }
        },
        "/me/whitelist/{target}": {
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile:write"
                        ]
                    }
                ],
                "description": "Adds target to the whitelist of the current user",
                "tags": [
                    "me",
                    "whitelist"
                ],
                "operationId": "NewWhitelisted"
            }
        },
        "/me/whitelisting": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "me",
                    "info",
                    "whitelisting"
                ],
                "summary": "Shows the whitelisting informations for the current user",
                "operationId": "getMeWhitelisted"
            }
        },
        "/projects/{id}": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "projects:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "project",
                    "info"
                ],
                "summary": "Shows the basic informations for the specified project",
                "operationId": "getProjectInfo"
            }
        },
        "/projects/{id}/followers": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "projects:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "project",
                    "info",
                    "followers"
                ],
                "summary": "Shows the followers informations for the specified project",
                "operationId": "getProjectFollowers"
            }
        },
        "/projects/{id}/members": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "projects:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "project",
                    "info",
                    "members"
                ],
                "summary": "Shows the members informations for the specified project",
                "operationId": "getProjectMembers"
            }
        },
        "/projects/{id}/posts": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:read"
                        ]
                    }
                ],
                "description": "This will show the last posts on the project board by default.\nYou can personalize the request via query string parameters",
                "tags": [
                    "project",
                    "posts"
                ],
                "summary": "List posts on project board, filtered by some parameters.",
                "operationId": "getProjectPosts"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:write"
                        ]
                    }
                ],
                "description": "Creates a new post on the specified project board",
                "tags": [
                    "project",
                    "post"
                ],
                "operationId": "NewProjectPost"
            }
        },
        "/projects/{id}/posts/{pid}": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:read"
                        ]
                    }
                ],
                "description": "This will show the last comments on the post by default.\nYou can personalize the request via query string parameters",
                "tags": [
                    "project",
                    "post"
                ],
                "summary": "Shows selected posts with id pid on specified project board",
                "operationId": "getProjectPost"
            },
            "put": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:write"
                        ]
                    }
                ],
                "description": "Update the speficied post on the specified project board",
                "tags": [
                    "project",
                    "post"
                ],
                "operationId": "EditProjectPost"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:write"
                        ]
                    }
                ],
                "description": "Delete the post on the specified project board",
                "tags": [
                    "project",
                    "post"
                ],
                "operationId": "DeleteProjectPost"
            }
        },
        "/projects/{id}/posts/{pid}/bookmarks": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:read"
                        ]
                    }
                ],
                "description": "List the bookmarks of the post",
                "tags": [
                    "project",
                    "post",
                    "bookmarks"
                ],
                "operationId": "GetProjectPostBookmarks"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:write"
                        ]
                    }
                ],
                "description": "Adds a new bookmark on the current post",
                "tags": [
                    "project",
                    "post",
                    "vote"
                ],
                "operationId": "NewProjectPostBookmark"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:write"
                        ]
                    }
                ],
                "description": "Deletes the bookmark on the current post",
                "tags": [
                    "project",
                    "post",
                    "vote"
                ],
                "operationId": "DeleteProjectPostBookmark"
            }
        },
        "/projects/{id}/posts/{pid}/comments": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "project_comments:read"
                        ]
                    }
                ],
                "description": "This will show the last posts on the project board by default.\nYou can personalize the request via query string parameters",
                "tags": [
                    "project",
                    "post",
                    "comments"
                ],
                "summary": "List comments on specified post, filtered by some parameters.",
                "operationId": "getProjectPostComments"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "project_comments:write"
                        ]
                    }
                ],
                "description": "Creates a new post on the specified project board",
                "tags": [
                    "project",
                    "post",
                    "comment"
                ],
                "operationId": "NewProjectPostComment"
            }
        },
        "/projects/{id}/posts/{pid}/comments/{cid}": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "project_comments:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "project",
                    "post",
                    "comment"
                ],
                "summary": "Shows selected comment on specified post, filtered by some parameters.",
                "operationId": "GetProjectPostComment"
            },
            "put": {
                "security": [
                    {
                        "oauth": [
                            "project_comments:write"
                        ]
                    }
                ],
                "description": "Update the speficied comment on the specified project post",
                "tags": [
                    "project",
                    "post",
                    "comment"
                ],
                "operationId": "EditProjectPostComment"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "project_comments:write"
                        ]
                    }
                ],
                "description": "Delete the specified comment on the speficied project post",
                "tags": [
                    "project",
                    "post"
                ],
                "operationId": "DeleteProjectPostComment"
            }
        },
        "/projects/{id}/posts/{pid}/comments/{cid}/votes": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "project_comments:read"
                        ]
                    }
                ],
                "description": "List the votes on the comment",
                "tags": [
                    "project",
                    "post",
                    "comments",
                    "votes"
                ],
                "operationId": "GetProjectPostCommentsVotes"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "project_comments:write"
                        ]
                    }
                ],
                "description": "Adds a new vote on the current project post comment",
                "tags": [
                    "project",
                    "post",
                    "comment",
                    "vote"
                ],
                "operationId": "NewProjectPostCommentVote"
            }
        },
        "/projects/{id}/posts/{pid}/locks": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:read"
                        ]
                    }
                ],
                "description": "List the locks of the post",
                "tags": [
                    "project",
                    "post",
                    "locks"
                ],
                "operationId": "GetProjectPostLock"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:write"
                        ]
                    }
                ],
                "description": "Adds a new lock on the current post",
                "tags": [
                    "project",
                    "post",
                    "vote"
                ],
                "operationId": "NewProjectPostLock"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:write"
                        ]
                    }
                ],
                "description": "Deletes the lock on the current post",
                "tags": [
                    "project",
                    "post",
                    "vote"
                ],
                "operationId": "DeleteProjectPostLock"
            }
        },
        "/projects/{id}/posts/{pid}/locks/{target}": {
            "post": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:write"
                        ]
                    }
                ],
                "description": "Locks the notification from the target user to the current logged user, on the specified post",
                "tags": [
                    "project",
                    "post",
                    "vote"
                ],
                "operationId": "NewUserNewPostProjectLock"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:write"
                        ]
                    }
                ],
                "description": "Deletes the lock  for the notification of the target user on the specified post",
                "tags": [
                    "project",
                    "post",
                    "vote"
                ],
                "operationId": "DeleteProjectPostUserLock"
            }
        },
        "/projects/{id}/posts/{pid}/lurks": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:read"
                        ]
                    }
                ],
                "description": "List the lurks of the post",
                "tags": [
                    "project",
                    "post",
                    "bookmarks"
                ],
                "operationId": "GetProjectPostLurks"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:write"
                        ]
                    }
                ],
                "description": "Adds a new lurk on the current post",
                "tags": [
                    "project",
                    "post",
                    "vote"
                ],
                "operationId": "NewProjectPostLurk"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:write"
                        ]
                    }
                ],
                "description": "Deletes the lurk on the current post",
                "tags": [
                    "project",
                    "post",
                    "vote"
                ],
                "operationId": "DeleteProjectPostLurk"
            }
        },
        "/projects/{id}/posts/{pid}/votes": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:read"
                        ]
                    }
                ],
                "description": "List the votes of the post",
                "tags": [
                    "project",
                    "post",
                    "votes"
                ],
                "operationId": "GetProjectPostVotes"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "project_messages:write"
                        ]
                    }
                ],
                "description": "Adds a new vote on the current post",
                "tags": [
                    "project",
                    "post",
                    "vote"
                ],
                "operationId": "NewProjectPostVote"
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "users",
                    "info"
                ],
                "summary": "Shows the basic informations for the specified user",
                "operationId": "GetUserInfo"
            }
        },
        "/users/{id}/blacklist": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "users",
                    "blacklist"
                ],
                "summary": "Show the blacklist of the specified user",
                "operationId": "GetBlacklist"
            }
        },
        "/users/{id}/blacklisting": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "users",
                    "blacklisting"
                ],
                "summary": "Show the user that placed the specified user in their blacklist",
                "operationId": "GetBlacklisting"
            }
        },
        "/users/{id}/followers": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "users",
                    "info",
                    "followers"
                ],
                "summary": "Shows the followers informations for the specified user",
                "operationId": "GetUserFollowers"
            }
        },
        "/users/{id}/following/projects": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "project",
                    "info",
                    "following"
                ],
                "summary": "Shows the following informations for the specified user",
                "operationId": "GetProjectFollowing"
            }
        },
        "/users/{id}/following/users": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "users",
                    "info",
                    "following"
                ],
                "summary": "Shows the following informations for the specified user",
                "operationId": "GetUserFollowing"
            }
        },
        "/users/{id}/friends": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "users",
                    "info",
                    "friends"
                ],
                "summary": "Shows the friends informations for the specified user",
                "operationId": "GetUserFriends"
            }
        },
        "/users/{id}/posts": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:read"
                        ]
                    }
                ],
                "description": "This will show the last posts on the user board by default.\nYou can personalize the request via query string parameters",
                "tags": [
                    "users",
                    "posts"
                ],
                "summary": "List posts on user board, filtered by some parameters.",
                "operationId": "GetUserPosts"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Creates a new post on the specified user board",
                "tags": [
                    "users",
                    "post"
                ],
                "operationId": "NewUserPost"
            }
        },
        "/users/{id}/posts/{pid}": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:read"
                        ]
                    }
                ],
                "description": "This will show the last comments on the post by default.\nYou can personalize the request via query string parameters",
                "tags": [
                    "users",
                    "post"
                ],
                "summary": "Shows selected posts with id pid on specified user board",
                "operationId": "GetUserPost"
            },
            "put": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Update the speficied post on the specified user board",
                "tags": [
                    "users",
                    "post"
                ],
                "operationId": "EditUserPost"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Delete the post on the specified user board",
                "tags": [
                    "users",
                    "post"
                ],
                "operationId": "DeleteUserPost"
            }
        },
        "/users/{id}/posts/{pid}/bookmarks": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:read"
                        ]
                    }
                ],
                "description": "List the bookmarks of the post",
                "tags": [
                    "users",
                    "post",
                    "bookmarks"
                ],
                "operationId": "GetUserPostBookmarks"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Adds a new bookmark on the current post",
                "tags": [
                    "users",
                    "post",
                    "vote"
                ],
                "operationId": "NewUserPostBookmark"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Deletes the bookmark on the current post",
                "tags": [
                    "users",
                    "post",
                    "vote"
                ],
                "operationId": "DeleteUserPostBookmark"
            }
        },
        "/users/{id}/posts/{pid}/comments": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:read"
                        ]
                    }
                ],
                "description": "This will show the last posts on the user board by default.\nYou can personalize the request via query string parameters",
                "tags": [
                    "users",
                    "post",
                    "comments"
                ],
                "summary": "List comments on specified post, filtered by some parameters.",
                "operationId": "GetUserPostComments"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:write"
                        ]
                    }
                ],
                "description": "Creates a new post on the specified user board",
                "tags": [
                    "users",
                    "post",
                    "comment"
                ],
                "operationId": "NewUserPostComment"
            }
        },
        "/users/{id}/posts/{pid}/comments/{cid}": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "users",
                    "post",
                    "comment"
                ],
                "summary": "Shows selected comment on specified post, filtered by some parameters.",
                "operationId": "GetUserPostComment"
            },
            "put": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:write"
                        ]
                    }
                ],
                "description": "Update the speficied comment on the specified users post",
                "tags": [
                    "users",
                    "post",
                    "comment"
                ],
                "operationId": "EditUserPostComment"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:write"
                        ]
                    }
                ],
                "description": "Delete the specified comment on the speficied users post",
                "tags": [
                    "users",
                    "post"
                ],
                "operationId": "DeleteUserPostComment"
            }
        },
        "/users/{id}/posts/{pid}/comments/{cid}/votes": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:read"
                        ]
                    }
                ],
                "description": "List the votes on the comment",
                "tags": [
                    "users",
                    "post",
                    "comments",
                    "votes"
                ],
                "operationId": "GetUserPostCommentsVotes"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_comments:write"
                        ]
                    }
                ],
                "description": "Adds a new vote on the current users post comment",
                "tags": [
                    "users",
                    "post",
                    "comment",
                    "vote"
                ],
                "operationId": "NewUserPostCommentVote"
            }
        },
        "/users/{id}/posts/{pid}/locks": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:read"
                        ]
                    }
                ],
                "description": "List the locks of the post",
                "tags": [
                    "users",
                    "post",
                    "locks"
                ],
                "operationId": "GetUserPostLock"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Adds a new lock on the current post",
                "tags": [
                    "users",
                    "post",
                    "vote"
                ],
                "operationId": "NewUserPostLock"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Deletes the lock on the current post",
                "tags": [
                    "users",
                    "post",
                    "vote"
                ],
                "operationId": "DeleteUserPostLock"
            }
        },
        "/users/{id}/posts/{pid}/locks/{target}": {
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Locks the notification from the target user to the current logged user, on the specified post",
                "tags": [
                    "users",
                    "post",
                    "vote"
                ],
                "operationId": "NewUserNewPostUserLock"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Deletes the lock for the notification of the target user on the specified post",
                "tags": [
                    "users",
                    "post",
                    "vote"
                ],
                "operationId": "DeleteUserPostUserLock"
            }
        },
        "/users/{id}/posts/{pid}/lurks": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:read"
                        ]
                    }
                ],
                "description": "List the lurks of the post",
                "tags": [
                    "users",
                    "post",
                    "bookmarks"
                ],
                "operationId": "GetUserPostLurks"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Adds a new lurk on the current post",
                "tags": [
                    "users",
                    "post",
                    "vote"
                ],
                "operationId": "NewUserPostLurk"
            },
            "delete": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Deletes the lurk on the current post",
                "tags": [
                    "users",
                    "post",
                    "vote"
                ],
                "operationId": "DeleteUserPostLurk"
            }
        },
        "/users/{id}/posts/{pid}/votes": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:read"
                        ]
                    }
                ],
                "description": "List the votes of the post",
                "tags": [
                    "users",
                    "post",
                    "votes"
                ],
                "operationId": "GetUserPostVotes"
            },
            "post": {
                "security": [
                    {
                        "oauth": [
                            "profile_messages:write"
                        ]
                    }
                ],
                "description": "Adds a new vote on the current post",
                "tags": [
                    "users",
                    "post",
                    "vote"
                ],
                "operationId": "NewUserPostVote"
            }
        },
        "/users/{id}/whitelist": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "users",
                    "whitelist"
                ],
                "summary": "Show the whitelist of the specified user",
                "operationId": "GetWhitelist"
            }
        },
        "/users/{id}/whitelisting": {
            "get": {
                "security": [
                    {
                        "oauth": [
                            "profile:read"
                        ]
                    }
                ],
                "description": "You can personalize the request via query string parameters",
                "tags": [
                    "users",
                    "whitelisting"
                ],
                "summary": "Show the user that placed the specified user in their whitelist",
                "operationId": "GetWhitelisting"
            }
        }
    },
    "securityDefinitions": {
        "oauth2_implicit": {
            "description": "OAuth2 implicit flow",
            "type": "oauth2",
            "flow": "implicit",
            "authorizationUrl": "https://www.nerdz.eu/oauth2/authorize.php?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=token",
            "scopes": {
                "base:read": "Grants complete read permissions.",
                "base:write": "Grants complete write permissions.",
                "followers:read": "Grants read access to user followers.",
                "followers:write": "Grants write access to user followers.",
                "following:read": "Grants read access to user following.",
                "following:write": "Grants write access to user following.",
                "friends:read": "Grants read access to user friends.",
                "friends:write": "Grants write access to user friends.",
                "messages:read": "Grants read access to messages in home, profiles and projects. Note that this scope includes profile_messages:read and project_messages:read.",
                "messages:write": "Grants write access to messages on profiles and projects. Note that this scope includes profile_messages:write and project_messages:write.",
                "notifications:read": "Grants read access to user notifications.",
                "notifications:write": "Grant write access to user notifications. This scope is necessary when the client needs to set as read a notification.",
                "pms:read": "Grants read access to user private messages.",
                "pms:write": "Grants write access to user private messages.",
                "profile:read": "Grants read access to profile info.",
                "profile:write": "Grants write access to profile info.",
                "profile_comments:read": "Grants read access to comments in profile posts.",
                "profile_comments:write": "Grants write access to comments in profile posts.",
                "profile_messages:read": "Grants read access to messages on profiles. Note that this scope includes profile_comments:read.",
                "profile_messages:write": "Grants write access to messages on profiles. Note that this scope includes profile_comments:write.",
                "project_comments:read": "Grants read access to comments in project posts.",
                "project_comments:write": "Grants write access to comments in project posts.",
                "project_messages:read": "Grants read access to messages on projects.",
                "project_messages:write": "Grants write access to messages on projects.",
                "projects:read": "Grants read access to projects info.",
                "projects:write": "Grants write access to projects info."
            }
        }
    }
}
